version: "3"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: flatmate
      POSTGRES_USER: purrweb
      POSTGRES_PASSWORD: purrweb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
